In [1]:
%%capture

import os
os.environ["USE_TF"] = "0"

from datasets import concatenate_datasets, DatasetDict
from transformers import Trainer
from transformers import TrainingArguments

import import_ipynb
from a_glance_at_dataset_and_tokenizer import langs, panx_ch, xlmr_tokenizer, tags
from create_model import (
    XLMRobertaForTokenClassification,
    tag_text,
    xlmr_config,
    device,
)
from tokenizing_text import encode_panx_dataset, panx_de_encoded, xlmr_tokenizer
from performance_measures import align_predictions

In [2]:
import gc
import torch
import create_model

if hasattr(create_model, "outputs"):
    del create_model.outputs

if hasattr(create_model, "xlmr_model"):
    del create_model.xlmr_model

gc.collect()
torch.cuda.empty_cache()

print(
    "allocated:",
    torch.cuda.memory_allocated() / 1024**3,
    "GB"
)

allocated: 0.007935047149658203 GB

In [3]:
num_epochs = 3
batch_size = 24
logging_steps = len(panx_de_encoded["train"]) // batch_size
xlmr_model_name = "xlm-roberta-base"
model_name = f"{xlmr_model_name}-finetuned-panx-de"

In [4]:
training_args = TrainingArguments(
    output_dir=model_name, log_level="error", num_train_epochs=num_epochs,
    per_device_train_batch_size=batch_size,
    per_gpu_eval_batch_size=batch_size, eval_strategy="epoch",
    save_steps=1e6, weight_decay=0.01, disable_tqdm=False,
    logging_steps=logging_steps, push_to_hub=True,
)

In [4]:
from huggingface_hub import notebook_login

notebook_login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [5]:
from seqeval.metrics import f1_score

def compute_metrics(eval_pred):
    y_pred, y_true = align_predictions(eval_pred.predictions, eval_pred.label_ids)

    return {"f1": f1_score(y_true, y_pred)}

In [6]:
from transformers import DataCollatorForTokenClassification

data_collator = DataCollatorForTokenClassification(xlmr_tokenizer)

In [7]:
def model_init():
    return (XLMRobertaForTokenClassification
           .from_pretrained(xlmr_model_name, config=xlmr_config)
           .to(device))

In [19]:
trainer = Trainer(model_init=model_init, args=training_args,
                  data_collator=data_collator, compute_metrics=compute_metrics,
                  train_dataset=panx_de_encoded["train"],
                  eval_dataset=panx_de_encoded["validation"],
                  processing_class=xlmr_tokenizer)

In [ ]:
trainer.train()
trainer.push_to_hub(commit_message="Training Completed!")

2026/09/09 12:09:41 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.schemas
2026/09/09 12:09:41 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.tables
2026/09/09 12:09:41 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.types
2026/09/09 12:09:41 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.constraints
2026/09/09 12:09:41 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.defaults
2026/09/09 12:09:41 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.comments
2026/09/09 12:09:42 INFO alembic.runtime.migration: Context impl SQLiteImpl.
2026/09/09 12:09:42 INFO alembic.runtime.migration: Will assume non-transactional DDL.

In [10]:
trained_model = XLMRobertaForTokenClassification.from_pretrained(
    model_name
).to(device)

In [11]:
text_de = "Jeff Dean ist ein Informatiker bei Google in Kalifornien"
tag_text(text_de, tags, trained_model, xlmr_tokenizer)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
Tokens,<s>,▁Jeff,▁De,an,▁ist,▁ein,▁Informati,ker,▁bei,▁Google,▁in,▁Kaliforni,en,</s>
Tags,O,B-PER,I-PER,I-PER,O,O,O,O,O,B-ORG,O,B-LOC,I-LOC,O

In [8]:
def concatenate_splits(corpora):
    multi_corpus = DatasetDict()
    for split in corpora[0].keys():
        multi_corpus[split] = concatenate_datasets(
            [corpus[split] for corpus in corpora]
        ).shuffle(seed=42)
    return multi_corpus

In [9]:
panx_fr_encoded = encode_panx_dataset(panx_ch['fr'])
panx_de_fr_encoded = concatenate_splits([panx_de_encoded, panx_fr_encoded])

In [10]:
training_args.logging_steps = len(panx_de_fr_encoded["train"]) // batch_size
training_args.push_to_hub = False
training_args.output_dir = "xlm-roberta-base-finetuned-panx-de-fr"

In [11]:
trainer = Trainer(
    model_init=model_init, args=training_args, processing_class=xlmr_tokenizer,
    data_collator=data_collator, compute_metrics=compute_metrics,
    train_dataset=panx_de_fr_encoded["train"], eval_dataset=panx_de_fr_encoded["validation"]
)

In [ ]:
trainer.train()

In [29]:
def evaluate_lang_performance(lang, trainer):
    panx_ds = encode_panx_dataset(panx_ch[lang])
    return get_f1_score(trainer, panx_ds["test"])

In [ ]:
for lang in langs:
    f1 = evaluate_lang_performance(lang, trainer)
    print(f"F1-Score of [de-fr] model on [{lang}] dataset: {f1:.3f}")

In [ ]:
def train_on_subset(dataset, num_samples):
    train_ds = dataset['train'].shuffle(seed=42).select(range(num_samples))
    val_ds = dataset['validation']
    test_ds = dataset['test']
    training_args.logging_steps = len(train_ds) // batch_size
    trainer = Trainer(model_init=model_init, args=training_args,
        data_collator=data_collator, compute_metrics=compute_metrics, 
        train_dataset=train_ds, eval_dataset=val_ds, processing_class=xlmr_tokenizer,
    )
    trainer.train()

    if training_args.push_to_hub:
        trainer.push_to_hub(commit_message="Training Completed!")

    f1_score = get_f1_score(trainer, test_ds)
    return pd.DataFrame.from_dict(
        {"num_samples": [len(train_ds)], "f1_score": [f1_score]}
    )

In [ ]:
corpora = [panx_de_encoded]
for lang in langs[1:]:
    training_args.output_dir = f"xlm-roberta-finetuned-panx-{lang}"
    ds_encoded = encode_panx_dataset(panx_ch[lang])
    metrics = train_on_subset(ds_encoded, ds_encoded["train"].num_rows)
    f1_scores[lang][lang] = metrics["f1_score"][0]
    corpora.append(ds_encoded)

In [ ]:
corpora_encoded = concatenate_datasets(corpora)
training_args.logging_steps = len(corpora_encoded)